name = "Acinetobacter_baumannii_K"
keyword = "ab_k"
genbank = "Acinetobacter_baumannii_K.gbk"
organism = "Acinetobacter baumannii"
taxon = 470
antigen = "Capsular polysaccharide"
pathway = "Wzx/Wzy-dependent"
prefix = "K"
version = "3.2.4"
id_threshold = 85.0
doi = [ "10.1099/mgen.0.000878",]
owner = "johannajkenyon"
repo = "Acinetobacter_baumannii_surface_polysaccharide_locus_databases"
branch = "main"

[contact]
"Johanna Kenyon" = "j.kenyon@griffith.edu.au"

[phenotype_logic]
"K3-v1" = { loci = ["KL3", "KL22"], inactive_genes = ["gtr6"] }
"K1-Ac-WzyGI1" = { loci = ["KL1"], extra_genes = ["wzyGI1", "atr25"] }
"K1-WzyGI1" = { loci = ["KL1"], extra_genes = ["wzyGI1"] }
"K1-Ac" = { loci = ["KL1"], extra_genes = ["atr25"] }
"K5-Ac" = { loci = ["KL5"], extra_genes = ["atr30"] }
"K19-Ac-WzyGI1" = { loci = ["KL19"], extra_genes = ["wzyGI1", "atr25"] }
"K19-WzyGI1" = { loci = ["KL19"], extra_genes = ["wzyGI1"] }
"K24-WzyGI2" = { loci = ["KL24"], extra_genes = ["wzyGI2"] }
"K46-Ac" = { loci = ["KL46"], extra_genes = ["atr29"] }
"K58-8ePse" = { loci = ["KL58"], extra_genes = ["epaA", "epaB"] }
"K58-Ac" = { loci = ["KL58"], extra_genes = ["atr44"] }
"K58-Wzy1Ph" = { loci = ["KL58"], extra_genes = ["wzy1Ph"] }
"K58-Wzy2Ph" = { loci = ["KL58"], extra_genes = ["wzy2Ph"] }
"K58-Wzy1Ph-Wzy2Ph" = { loci = ["KL58"], extra_genes = ["wzy1Ph", "wzy2Ph"] }
"K127-Wzy1Ph" = { loci = ["KL127"], extra_genes = ["wzy1Ph"] }
"K135-8ePse" = { loci = ["KL135"], extra_genes = ["epaA", "epaB"] }
